import { Header } from "@/modules/index.client";
import { MantineProvider } from "@mantine/core";
import type { Metadata } from "next";

import '@mantine/core/styles.css';
import 'swiper/css';
import 'swiper/css/pagination';
import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MantineProvider>
          <Header />
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
